// <auto-generated />
namespace TP_Dojo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class migInit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migInit));
        
        string IMigrationMetadata.Id
        {
            get { return "202009230738594_migInit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
